### ISSUE TITLE
Migration to node16 (node12 becomes deprecated)

### ISSUE THREAD

**Issue by just1not2** [raynigon/sendgrid-mail-action#5]
As explained in [the Github blog](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/), node12 is becoming deprecated. The following warning appears when using this Github Action:

_Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: raynigon/sendgrid-mail-action_

Could you please update to node16 in the [action.yaml](https://github.com/raynigon/sendgrid-mail-action/blob/main/action.yaml) file to fix this deprecation warning?

**Comment by raynigon** [comment]
Released with 1.0.3

See https://github.com/raynigon/sendgrid-mail-action/releases/tag/1.0.3
