### ISSUE TITLE
Update actions/core dependency

### ISSUE THREAD

**Issue by just1not2** [raynigon/sendgrid-mail-action#7]
As explained in a [Github blog note](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/), a security update have been added in `v1.10.0` of `@actions/core`. As of today, a warning is triggered when using this Github Action:

_The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/_

Could you please update your `@actions/core` package (currently at `v1.2.7`)  to `v1.10.0` or higher to fix this problem?

**Comment by raynigon** [comment]
Released with https://github.com/raynigon/sendgrid-mail-action/releases/tag/1.0.4
